# Generated by Django 5.2.8 on 2025-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='flights.flight')),
            ],
        ),
    ]
